version: "3"
services:
  db:
    image: postgres:15.0
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: content-sync
    ports:
      - "6432:5432"
  content-puller:
    image: vhonta/content-puller:0.5.0
    restart: always
    env_file:
      - common.env
      - secret.env
    environment:
      DATALAKE_OUTPUT_DIR: /opt/datalake
    volumes:
      - ./datalake:/opt/datalake
    depends_on:
      - db
  content-processor-launcher:
    image: vhonta/content-processor-launcher:0.5.0
    restart: always
    env_file:
      - common.env
      - secret.env
    environment:
      SPARK_HOME: /opt/spark
      ARTIFACT_DIR: /opt/job
      PROCESSOR_INPUT_PATH: /opt/datalake
      PROCESSOR_CHECKPOINT_LOCATION: /opt/checkpoint
      PROCESSOR_RESULT_PATH: /opt/processor-results
    depends_on:
      - db
    volumes:
      - ./spark-home:/opt/spark
      - ./content-processor-job/target/scala-2.13:/opt/job
      - ./datalake:/opt/datalake
      - ./checkpoint:/opt/checkpoint
      - ./processor-results:/opt/processor-results
  telegram-bot:
    image: vhonta/telegram-bot:0.5.0
    restart: always
    env_file:
      - common.env
      - secret.env
    environment:
      TELEGRAM_BINDING_PORT: 9092
    depends_on:
      - db
    ports:
      - "9092:9092"
