version: "3"
services:
  db:
    image: postgres:15.0
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: content-sync
    ports:
      - "6432:5432"
  content-puller:
    image: vhonta/content-puller:0.4.0
    restart: always
    env_file:
      - common.env
      - secret.env
    depends_on:
      - db
  content-processor:
    image: vhonta/content-processor-launcher:0.4.0
    restart: always
    env_file:
      - common.env
      - secret.env
    depends_on:
      - db
  telegram-bot:
    image: vhonta/telegram-bot:0.4.0
    restart: always
    env_file:
      - common.env
      - secret.env
    environment:
      TELEGRAM_BINDING_PORT: 9092
    depends_on:
      - db
    ports:
      - "9092:9092"
