version: "3"
services:
  db:
    image: postgres:15.0
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: content-sync
    ports:
      - "6432:5432"