version: "3"
services:
  db:
    image: postgres:15.0
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: news
    ports:
      - "6432:5432"
  news-puller:
    image: vhonta/news-puller:0.1.0
    restart: always
    env_file:
      - common.env
      - secret.env
    depends_on:
      - db
  news-processor:
    image: vhonta/news-processor:0.1.0
    restart: always
    env_file:
      - common.env
      - secret.env
    depends_on:
      - db
  telegram-push:
    image: vhonta/telegram-push:0.1.0
    restart: always
    env_file:
      - common.env
      - secret.env
    depends_on:
      - db
