name: Test
on:
  pull_request:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
jobs:
  content-sync-test:
    uses: ./.github/workflows/test_scala.yaml
    with: 
      workdir: content-sync
  cryptostock-test:
    uses: ./.github/workflows/test_scala.yaml
    with: 
      workdir: cryptostock